/*
Autogenerated file, using creds/credgen.go. Do not modify.

In order to run this utility using your own Google API credentials, place
your "credentials.json" file in the "creds/" folder.
Obtain such file following these instructions:
https://developers.google.com/identity/protocols/OAuth2InstalledApp
*/

package gsheets

import (
	"io/ioutil"
)

var credentialsRaw = ``

const credentialsFile string = "creds/credentials.json"

func GetCredentials() []byte {
	if b, err := ioutil.ReadFile(credentialsFile); err == nil {
		return b
	}
	return []byte(credentialsRaw)
}
